FROM alpine:3.20.3

RUN mkdir -p /home/DATA/www-deploy/meatbox-web2/src/main/webaap/ \ 
            /home/DATA/share/meatbox2/static && \
    chown www:www -R /home && \
    adduser -D -u 1001 -g 1001 www
    
WORKDIR /home/DATA/www-deploy/meatbox-web2/src/main/webaap/

COPY --chown=www:www . .

CMD ["./deploy.sh"]